### ISSUE TITLE
Roadmap for getting infi-ctx to feature parity with RWKV main branch

### ISSUE THREAD

**Issue by PicoCreator** [PicoCreator/RWKV-LM-LoRA#5]
The following is the list of missing features in the RWKV infi-ctx branch, for it to be a full replacement to the main RWKV trainer

- support for following data formats (with chunking?)
   - [x]  text files
   - [ ]  numpy files
   - [x]  binidx
- [x]  support for model init weight
- [ ]  support for model resize weights (init from smaller to bigger model)
- [x]  support for world tokenizer
- [x]  Learning Rate init -> Learning Rate Final support
- [ ]  warmup steps?
- [ ]  helper script to add new tokens to existing model
